create table if not exists public.system_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  notification_type text not null,
  person_id text,
  person_name text,
  position text,
  term_start_date text,
  term_end_date text not null,
  recipient_email text not null,
  notification_key text not null unique,
  status text not null default 'pending'
    check (status in ('pending', 'sending', 'sent', 'failed', 'skipped')),
  trigger_at timestamptz,
  provider_message_id text,
  error_message text,
  retry_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notif_type_status
  on public.notification_events (notification_type, status);

create index if not exists idx_notif_end_date
  on public.notification_events (term_end_date);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor text not null default 'system',
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_created
  on public.audit_log (created_at);

alter table public.system_settings enable row level security;
alter table public.notification_events enable row level security;
alter table public.audit_log enable row level security;
